#!/bin/sh
# regenerate or verify src/ray.mach, the flat public surface.
#   tools/surface.sh gen     rewrite src/ray.mach from the split modules
#   tools/surface.sh check   exit nonzero if src/ray.mach is out of date
set -eu
cd "$(dirname "$0")/.."

MODULES="raylib raymath rcamera"

generate() {
    cat <<'EOF'
# the flat public surface of the Raylib bindings
#
# GENERATED by tools/surface.sh; do not edit by hand. run
# `tools/surface.sh gen` after changing any split module's public surface.
#
# re-exports every binding under one namespace so consumers can write
# `use ray.raylib;` and reach the whole API as ray.init(),
# ray.create_window(), ray.KEY_ESCAPE, and so on. the split modules
# (ray.core, ray.window, ...) remain importable individually.

use ray.c;
EOF
    for m in $MODULES; do printf 'use ray.%s;\n' "$m"; done
    #printf '\nfwd c.Vidmode;\nfwd c.Gammaramp;\nfwd c.Image;\nfwd c.Gamepadstate;\n'
    for m in $MODULES; do
        grep -oE '^pub (val|fun|rec|def) [A-Za-z_][A-Za-z0-9_]*' "output/$m.mach" |
            awk -v m="$m" '{print m"."$3}'
    done | LC_ALL=C sort | awk '{print "fwd "$1";"}'
}

case "${1:-}" in
    gen)   generate > output/ray.mach ;;
    check) generate | diff -u output/ray.mach - >&2 || {
               echo "src/ray.mach is out of date; run tools/surface.sh gen" >&2
               exit 1
           } ;;
    *)     echo "usage: tools/surface.sh gen|check" >&2; exit 2 ;;
esac
