#!/bin/sh
set -eu
cd "$(dirname "$0")/.."

MODULES="raylib raymath rcamera"

generate() {
    cat <<'EOF'
# the flat public surface of the Raylib bindings
#
# GENERATED by tools/surface.sh; do not edit by hand. run
# `tools/surface.sh gen` after changing any split module's public surface.
#
# re-exports every binding under one namespace so consumers can write
# `use raylib.ra;` and reach the whole API as ra.init_window(...),
# ra.Vector2, ra.KEY_ESCAPE, and so on. the split modules
# (raylib.raylib,raylib.raymath,raylib.rcamera) remain importable individually.

#use ra.xxx;
EOF
    for m in $MODULES; do printf 'use raylib.%s;\n' "$m"; done
    for m in $MODULES; do
        grep -oE '^pub (val|fun|rec|def) [A-Za-z_][A-Za-z0-9_]*' "output/$m.mach" |
            awk -v m="$m" '{print m"."$3}'
    done | LC_ALL=C sort | awk -F. ' {
        if (!($NF in seen)) {
            seen[$NF] = $0
            print "fwd "$0";"
        } else {
            print "# dup " $0 " (shadowed by " seen[$NF] ")" > "/dev/stderr"
        }
    } '
}

case "${1:-}" in
    gen)   generate 2>/dev/null > output/ra.mach ;;
    check) generate | diff -u output/ra.mach - >&2 || {
               echo "src/ra.mach is out of date; run tools/surface.sh gen" >&2
               exit 1
           } ;;
    *)     echo "usage: tools/surface.sh gen|check" >&2; exit 2 ;;
esac
